apiVersion: v1
kind: Pod
metadata:
  name: maven-build-curl-pod
spec:
  containers:
  - name: maven
    image: maven:3.5.0
    command:
    - cat
    tty: true
  - name: curl
    image: curlimages/curl:7.65.3
    command:
    - cat
    tty: true
  restartPolicy: Never
